# Day 3 – NumPy Tasks
**Topics:** NumPy arrays, indexing, and mathematical operations

**Expected Outcome:** NumPy fundamentals completed.

## 1. Import NumPy

In [2]:
import numpy as np

## 2. Creating Arrays
Create 1D and 2D arrays, plus some built-in array generators.

In [ ]:
# 1D array from a list
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)

# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr2)

# Built-in generators
zeros = np.zeros((2, 3))                  
ones = np.ones((3, 3))                    
rng = np.arange(0, 10, 2)                
lin = np.linspace(0, 1, 5)                
rand = np.random.randint(1, 100, (3, 3))  

print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nArange:", rng)
print("\nLinspace:", lin)
print("\nRandom 3x3:\n", rand)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Arange: [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]

Random 3x3:
 [[93  3 58]
 [70  3 23]
 [60 80 40]]


In [4]:
# Array properties
print("Shape:", arr2.shape)   # (rows, columns)
print("Dimensions:", arr2.ndim)
print("Size:", arr2.size)     # total elements
print("Data type:", arr2.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64


## 3. Indexing & Slicing

In [5]:
arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice [1:4]:", arr[1:4])
print("Reversed:", arr[::-1])

First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Reversed: [50 40 30 20 10]


In [6]:
# 2D indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Element at row 1, col 2:", matrix[1, 2])
print("First column:", matrix[:, 0])
print("First row:", matrix[0, :])
print("Sub-matrix [0:2, 1:3]:\n", matrix[0:2, 1:3])

Element at row 1, col 2: 6
First column: [1 4 7]
First row: [1 2 3]
Sub-matrix [0:2, 1:3]:
 [[2 3]
 [5 6]]


In [7]:
# Boolean indexing
nums = np.array([5, 12, 8, 20, 3])
print("Elements greater than 10:", nums[nums > 10])

Elements greater than 10: [12 20]


## 4. Mathematical Operations

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Square:", a ** 2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Square: [1 4 9]


In [9]:
# Aggregate functions
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Max:", np.max(a))
print("Min:", np.min(a))
print("Standard deviation:", np.std(a))

Sum: 6
Mean: 2.0
Max: 3
Min: 1
Standard deviation: 0.816496580927726


In [10]:
# Matrix operations
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Element-wise addition:\n", m1 + m2)
print("\nMatrix multiplication (dot product):\n", np.dot(m1, m2))
print("\nTranspose of m1:\n", m1.T)

Element-wise addition:
 [[ 6  8]
 [10 12]]

Matrix multiplication (dot product):
 [[19 22]
 [43 50]]

Transpose of m1:
 [[1 3]
 [2 4]]


## 5. Practice Task
A combined exercise using array creation, slicing, boolean indexing, and math operations.

In [11]:
# 1. Create a 5x5 array of random integers between 1 and 50
arr = np.random.randint(1, 50, (5, 5))
print("Original Array:\n", arr)

# 2. Extract the first two rows and first three columns
sub = arr[0:2, 0:3]
print("\nSubset (first 2 rows, first 3 cols):\n", sub)

# 3. Find all elements greater than 25
greater_25 = arr[arr > 25]
print("\nElements > 25:", greater_25)

# 4. Calculate row-wise and column-wise sums
row_sums = np.sum(arr, axis=1)
col_sums = np.sum(arr, axis=0)
print("\nRow sums:", row_sums)
print("Column sums:", col_sums)

# 5. Normalize the array (min-max scaling)
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print("\nNormalized array:\n", normalized)

Original Array:
 [[37  2 32 40 23]
 [38 12 24 47 46]
 [26  9 33 20 38]
 [10  2 44 23 30]
 [25 40 35 17 38]]

Subset (first 2 rows, first 3 cols):
 [[37  2 32]
 [38 12 24]]

Elements > 25: [37 32 40 38 47 46 26 33 38 44 30 40 35 38]

Row sums: [134 167 126 109 155]
Column sums: [136  65 168 147 175]

Normalized array:
 [[0.77777778 0.         0.66666667 0.84444444 0.46666667]
 [0.8        0.22222222 0.48888889 1.         0.97777778]
 [0.53333333 0.15555556 0.68888889 0.4        0.8       ]
 [0.17777778 0.         0.93333333 0.46666667 0.62222222]
 [0.51111111 0.84444444 0.73333333 0.33333333 0.8       ]]


## Summary
- Created 1D and 2D NumPy arrays using multiple methods
- Practiced indexing and slicing (including boolean indexing)
- Performed element-wise and matrix mathematical operations
- Combined all concepts in a practice task (subsetting, filtering, aggregation, normalization)

**Day 3 NumPy fundamentals: completed.**